=== Booswoos/STUDIA/HIH/dtd.dtd
<!ELEMENT spis (komentarz,towar+,usluga+)>
<!ELEMENT komentarz (#PCDATA)>
<!ELEMENT towar (inf,ilosc,suma,dostawa)>
<!ELEMENT inf (nazwa,rodzaj,producent,cena_sztuka,image)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT rodzaj (#PCDATA)>
<!ELEMENT producent (#PCDATA)>
<!ELEMENT cena_sztuka (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT ilosc (#PCDATA)>
<!ELEMENT suma (#PCDATA)>
<!ELEMENT dostawa (kurier,miasto,ulica,numer,data)> 
<!ELEMENT miasto (#PCDATA)>
<!ELEMENT ulica (#PCDATA)>
<!ELEMENT numer (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT usluga (rodzaj,wykonawca,koszt)>
<!ELEMENT wykonawca (firma, numerr)>
<!ELEMENT firma (#PCDATA)>
<!ELEMENT koszt (#PCDATA)>
<!ELEMENT kurier (przewoz,imie,nazwisko,tryb)>
<!ELEMENT przewoz (#PCDATA)>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT tryb (#PCDATA)>
<!ELEMENT numerr (kierunkowy,number)>
<!ELEMENT kierunkowy (#PCDATA)>
<!ENTITY miasto "Gdansk">
<!ENTITY kierunkowy SYSTEM "external.txt">
<!ENTITY % status "(TAK|NIE)">
<!ENTITY % ile "(1|2|3|4|5|6)">

<!ATTLIST komentarz zawartosc %ile; "2">
<!ATTLIST spis data_zamowienia CDATA #REQUIRED>
<!ATTLIST towar kod_produktu ID #REQUIRED>
<!ATTLIST towar data_zamowienia CDATA #REQUIRED> 
<!ATTLIST inf link CDATA  #IMPLIED>
<!ATTLIST usluga data_zlecenia CDATA #REQUIRED>
<!ATTLIST usluga id ID #REQUIRED>
<!ATTLIST wykonawca strona CDATA "https://google.com">
<!ATTLIST usluga przyjeto %status; "NIE">

=== Booswoos/STUDIA/HIH/xml_dtd.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE spis SYSTEM "dtd.dtd">

<spis  data_zamowienia="20.10.2020">

  <komentarz zawartosc="5">trzy towary dwie uslugi</komentarz>
  
  <towar kod_produktu="SSN-125-FM" data_zamowienia="2020-10-11">
    <inf link="https://botland.com.pl/pl/diody-led/4538-dioda-led-8mm-czerwona-10szt.html">
      <nazwa>Dioda LED 8mm czerwona</nazwa>
      <rodzaj>dioda</rodzaj>
      <producent>OEM</producent>
      <cena_sztuka>0.35</cena_sztuka>
      <image>img_xml/dioda.jpg</image>
    </inf>
    <ilosc>20</ilosc>
    <suma>7</suma>
    <dostawa>
      <kurier>
        <przewoz>GLS</przewoz>
        <imie>Wojciech</imie>
        <nazwisko>Stanczyk</nazwisko>
        <tryb>Express</tryb>
      </kurier>
      <miasto>Gdynia</miasto>
      <ulica>Partyzantow</ulica>
      <numer>65</numer>
      <data>2020-10-09</data>
    </dostawa>
  </towar>

  <towar kod_produktu="HWM-667-CC" data_zamowienia="23.10.2020">
    <inf link="https://botland.com.pl/pl/analogowe-czujniki-odleglosci/2707-sharp-gp2y0a60szlf-analogowy-czujnik-odleglosci-10-150cm-5v-pololu-2474.html">
      <nazwa>Sharp GP2Y0A60SZLF</nazwa>
      <rodzaj>czujnik</rodzaj>
      <producent>Pololu</producent>
      <cena_sztuka>69.90</cena_sztuka>
      <image>img_xml/czujnik.jpg</image>
    </inf>
    <ilosc>2</ilosc>
    <suma>139.98</suma>
    <dostawa>
      <kurier>
        <przewoz>FEDEX</przewoz>
        <imie>Andrzej</imie>
        <nazwisko>Woskowski</nazwisko>
        <tryb>Express</tryb>
      </kurier>
      <miasto>&miasto;</miasto>
      <ulica>Szeroka</ulica>
      <numer>34</numer>
      <data>2020-10-17</data>
    </dostawa>
  </towar>

  <towar kod_produktu="JKM-003-UG" data_zamowienia="2020-10-11">
    <inf link="https://botland.com.pl/pl/silniki-micro-pololu-seria-hp-high-power/13823-silnik-hp-2101-obustronny-wal-pololu-2216.html">
      <nazwa>Silnik HP 210:1</nazwa>
      <rodzaj>silnik</rodzaj>
      <producent>Pololu</producent>
      <cena_sztuka>62.90</cena_sztuka>
      <image>img_xml/silnik.jpg</image>
    </inf>
    <ilosc>6</ilosc>
    <suma>377.40</suma>
    <dostawa>
      <kurier>
        <przewoz>DPD</przewoz>
        <imie>Waclaw</imie>
        <nazwisko>Wawer</nazwisko>
        <tryb>Express</tryb>
      </kurier>
      <miasto>&miasto;</miasto>
      <ulica>Szeroka</ulica>
      <numer>34</numer>
      <data>2020-11-25</data>
    </dostawa>
  </towar>


  <usluga data_zlecenia="2020-10-11" id="U0" przyjeto="TAK">
    <rodzaj>Plytka PCB</rodzaj>
    <wykonawca strona="https://jlcpcb.com">
      <firma>JLCPCB</firma>
      <numerr>
        <kierunkowy>&kierunkowy;</kierunkowy>
        <number>657304234</number>
      </numerr>
    </wykonawca>
    <koszt>2.50</koszt>
  </usluga>


  <usluga data_zlecenia="2020-10-11" id="U1" przyjeto="NIE">
    <rodzaj>Odlew opon</rodzaj>
    <wykonawca strona="https://www.poliuretanyczaniec.pl">
      <firma>Poliuretany Czaniec</firma>
      <numerr>
        <kierunkowy>&kierunkowy;</kierunkowy>
        <number>334322729</number>
      </numerr>
    </wykonawca>
    <koszt>80</koszt>
  </usluga>

</spis>
