=== Booswoos/STUDIA/HIH/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="urn:My.Namespace"
            xmlns="urn:My.Namespace"
    elementFormDefault="qualified"
    
    xmlns:mstns="http://tempuri.org/XMLSchema.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>



  <xs:annotation>
   <xs:documentation xml:lang="pl">
     XML Schema do dziennego zestawienia.
   </xs:documentation>
  </xs:annotation>



  <xs:element name="spis" type="spisType"/>

  <xs:complexType name="spisType">
    <xs:sequence>
      <xs:element name="komentarz" type="listType"  minOccurs="1" maxOccurs="unbounded" ></xs:element>
      <xs:element name="towar" type="towarType" maxOccurs="unbounded"/>
      <xs:element name="usluga" type="uslugaType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="data_powstania" type="xs:date"/>
  </xs:complexType>

  <xs:complexType name="towarType">
    <xs:sequence>
      <xs:element name="inf" type="infType"> </xs:element>
      <xs:element name="ilosc" type="StringOrIntType"></xs:element>
      <xs:element ref="suma"></xs:element>
      <xs:element name="dostawa" type="dostawaType"></xs:element>
    </xs:sequence>
    <xs:attribute ref="kod_produktu"/>
    <xs:attribute ref="data_zamowienia"/>
  </xs:complexType>

  <xs:complexType name="infType">
    <xs:sequence>
      <xs:element name="nazwa" type="xs:string"></xs:element>
      <xs:element name="rodzaj" type="rodzajType"></xs:element>
      <xs:element name="producent" type="linkType"></xs:element>
      <xs:element name="cena_sztuka" type="cenaType"></xs:element>
      <xs:element ref="image" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="link" type="linkType" use="required"></xs:attribute>
  </xs:complexType>

  <xs:simpleType name="cenaType">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"></xs:minExclusive>
      <xs:maxExclusive value="5000"></xs:maxExclusive>      
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="rodzajType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="czujnik" />
      <xs:enumeration value="silnik" />
      <xs:enumeration value="dioda" />
      <xs:enumeration value="sterownik"/>
      <xs:enumeration value="mostek"/>
      <xs:enumeration value="plytka"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="dostawaType">
    <xs:sequence>
      <xs:element name="kurier" type="kurierInfo"></xs:element>
      <xs:element name="miasto" type="longStringType"></xs:element>
      <xs:element name="ulica" type="longStringType"></xs:element>
      <xs:element name="numer" type="xs:integer"></xs:element>
      <xs:element name="data" type="xs:date"></xs:element>
    </xs:sequence>
  </xs:complexType>


 

  <xs:element name="suma" type="sumaType"></xs:element>
  <xs:attribute name="kod_produktu" type="kodType"></xs:attribute>
  <xs:attribute name="data_zamowienia" type="xs:date"></xs:attribute>
  <xs:attribute name="data_zlecenia" type="xs:date"></xs:attribute>
  <xs:attribute name="id" type="shortStringType"></xs:attribute>
  <xs:attribute name="przyjeto" type="stanType"></xs:attribute>
  <xs:element name="link" type="linkType"></xs:element>
  <xs:element name="image" type="linkType"></xs:element>

  <xs:simpleType name ="stanType">
    <xs:restriction base="shortStringType">
      <xs:enumeration value="Tak"/>
      <xs:enumeration value="Nie"/>   
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="longStringType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="shortStringType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>

    <xs:simpleType name="sumaType">
     <xs:restriction base="xs:decimal">
       <xs:minExclusive value="1"/>
       <xs:maxExclusive value="10000"/>
     </xs:restriction>
    </xs:simpleType>

  <xs:simpleType name="kodType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}-/d{3}-/[A-Z]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="linkType">
    <xs:restriction base="xs:anyURI"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="StringOrIntType">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>

      <xs:simpleType>
        <xs:restriction base="xs:int"/>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
  
  <xs:complexType name="uslugaType">
    <xs:sequence>
      <xs:element name="rodzaj" type="longStringType"></xs:element>
      <xs:element name="wykonawca" type="wykonawcaType"></xs:element>
      <xs:element name="koszt" type="cenaType"></xs:element>
    </xs:sequence>
    <xs:attribute ref="data_zlecenia"></xs:attribute>
    <xs:attribute ref="id"></xs:attribute>
    <xs:attribute ref="przyjeto"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="wykonawcaType">
    <xs:sequence>
      <xs:element name="firma" type="longStringType"></xs:element>
      <xs:element name="numer" type="numerType"></xs:element>
    </xs:sequence>
    <xs:attribute name="strona" type="linkType"> </xs:attribute>
  </xs:complexType>

  <xs:complexType name="numerType" mixed="true">
    <xs:sequence>
      <xs:element name="kierunkowy" type="xs:decimal"></xs:element>
      <xs:element name ="number" type="numberType"></xs:element>
    </xs:sequence>
    
  </xs:complexType>

  <xs:simpleType name="numberType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{9}"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>



  <xs:simpleType name="info">
    <xs:restriction base="xs:string">
      <xs:enumeration value="express" />
      <xs:enumeration value="standard" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="kurierType">
    <xs:sequence>
      <xs:element name="przewoz" type="xs:string"/>
      <xs:element name="imie" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="kurierInfo">
    <xs:complexContent>
      <xs:extension base="kurierType">
        <xs:sequence>         
          <xs:element name="nazwisko" type="xs:string"/>
         <xs:element name="tryb" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="listType">
    <xs:list itemType="xs:string"/>
  </xs:simpleType>
  
  
</xs:schema>

=== Booswoos/STUDIA/HIH/xml.xml
<?xml version="1.0" encoding="utf-8"?>


<spis  xmlns:data_zamowienia="20.10.2020"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="urn:My.Namespace"
      xsi:schemaLocation="urn:My.Namespace schema.xsd">

  <komentarz>trzy towary dwie uslugi</komentarz>
  
  <towar xmlns:kod_produktu="SSN-125-FM" xmlns:data_zamowienia="2020-10-11">
    <inf link="https://botland.com.pl/pl/diody-led/4538-dioda-led-8mm-czerwona-10szt.html">
      <nazwa>Dioda LED 8mm czerwona</nazwa>
      <rodzaj>dioda</rodzaj>
      <producent>OEM</producent>
      <cena_sztuka>0.35</cena_sztuka>
      <image>img_xml/dioda.jpg</image>
    </inf>
    <ilosc>20</ilosc>
    <suma>7</suma>
    <dostawa>
      <kurier>
        <przewoz>GLS</przewoz>
        <imie>Wojciech</imie>
        <nazwisko>Stanczyk</nazwisko>
        <tryb>Express</tryb>
      </kurier>
      <miasto>Gdynia</miasto>
      <ulica>Partyzantow</ulica>
      <numer>65</numer>
      <data>2020-10-09</data>
    </dostawa>
  </towar>

  <towar xmlns:kod_produktu="HWM-667-CC" xmlns:data_zamowienia="23.10.2020">
    <inf link="https://botland.com.pl/pl/analogowe-czujniki-odleglosci/2707-sharp-gp2y0a60szlf-analogowy-czujnik-odleglosci-10-150cm-5v-pololu-2474.html">
      <nazwa>Sharp GP2Y0A60SZLF</nazwa>
      <rodzaj>czujnik</rodzaj>
      <producent>Pololu</producent>
      <cena_sztuka>69.90</cena_sztuka>
      <image>img_xml/czujnik.jpg</image>
    </inf>
    <ilosc>dwa</ilosc>
    <suma>139.98</suma>
    <dostawa>
      <kurier>
        <przewoz>FEDEX</przewoz>
        <imie>Andrzej</imie>
        <nazwisko>Woskowski</nazwisko>
        <tryb>Express</tryb>
      </kurier>
      <miasto>Gdansk</miasto>
      <ulica>Szeroka</ulica>
      <numer>34</numer>
      <data>2020-10-17</data>
    </dostawa>
  </towar>

  <towar xmlns:kod_produktu="JKM-003-UG" xmlns:data_zamowienia="2020-10-11">
    <inf link="https://botland.com.pl/pl/silniki-micro-pololu-seria-hp-high-power/13823-silnik-hp-2101-obustronny-wal-pololu-2216.html">
      <nazwa>Silnik HP 210:1</nazwa>
      <rodzaj>silnik</rodzaj>
      <producent>Pololu</producent>
      <cena_sztuka>62.90</cena_sztuka>
      <image>img_xml/silnik.jpg</image>
    </inf>
    <ilosc>6</ilosc>
    <suma>377.40</suma>
    <dostawa>
      <kurier>
        <przewoz>DPD</przewoz>
        <imie>Waclaw</imie>
        <nazwisko>Wawer</nazwisko>
        <tryb>Express</tryb>
      </kurier>
      <miasto>Gdansk</miasto>
      <ulica>Szeroka</ulica>
      <numer>34</numer>
      <data>2020-11-25</data>
    </dostawa>
  </towar>


  <usluga xmlns:data_zlecenia="2020-10-11" xmlns:id="6383839242" xmlns:przyjeto="Tak">
    <rodzaj>Plytka PCB</rodzaj>
    <wykonawca strona="https://jlcpcb.com">
      <firma>JLCPCB</firma>
      <numer>+<kierunkowy>40</kierunkowy><number>657304234</number></numer>
    </wykonawca>
    <koszt>2.50</koszt>
  </usluga>


  <usluga xmlns:data_zlecenia="2020-10-11" xmlns:id="6383839737" xmlns:przyjeto="Nie">
    <rodzaj>Odlew opon</rodzaj>
    <wykonawca strona="https://www.poliuretanyczaniec.pl">
      <firma>Poliuretany Czaniec</firma>
      <numer>+<kierunkowy>48</kierunkowy><number>334322729</number></numer>
    </wykonawca>
    <koszt>80</koszt>
  </usluga>

</spis>
